version: '3.1'
services:
  db:
    image: mdillon/postgis:9.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/app
    ports:
      - "5432:5432"
  redis:
    image: redis
    volumes:
      - redis_cache:/data
  web:
    environment:
      - DEBUG=false
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - ~/.ssh:/root/.ssh
      - bundle_cache:/bundle
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  postgres_data: {}
  bundle_cache: {}
  redis_cache: {}
